# Formalia

Please read the [assignment overview page](https://laura.alessandretti.com/comsocsci2026/wiki_pages/Assignments.html) carefully before proceeding. The page contains information about formatting (including formats etc), group sizes, and many other aspects of handing in the assignment. 

__If you fail to follow these simple instructions, it will negatively impact your grade!__

**Due date and time**: The assignment is due on Mar 3rd at 23:59. Hand in your Jupyter notebook file (with extension `.ipynb`) via DTU Learn _(Assignment 1)_. 

Remember to include in the first cell of your notebook:
* the link to your group's Git repository 
* group members' contributions

## Part 1: Ready Made vs Custom Made Data

> **Exercise: Ready made data vs Custom made data** In this exercise, I want to make sure you have understood they key points of my lecture and the reading. 
>
> 1. What are pros and cons of the custom-made data used in Centola's experiment (the first study presented in the lecture) and the ready-made data used in Nicolaides's study (the second study presented in the lecture)? You can support your arguments based on the content of the lecture and the information you read in Chapter 2.3 of the book __(answer in max 150 words)__.
> 2. How do you think these differences can influence the interpretation of the results in each study? __(answer in max 150 words)__

## Part 2: Find Researchers using the OpenAlex API

> **Exercise 3: Find potential Computational Social Scientists** In this exercise, we'll use the OpenAlex API to compile a list of researchers in the field of Computational Social Science, focusing on those who have attended the IC2S2 conference in 2025. This will not only later on help you understand the landscape of Computational Social Science research but also develop practical skills in data collection and analysis. 
>
> Please read the text of the whole exercise before starting to work on it. 
>
> **Steps**
> 
> 1. **Retreive data.** Consider the set of unique researcher names that you collected in Week 1, Exercise 3. Use the _authors_ endpoint of the [OpenAlex API](https://docs.openalex.org/api-entities/authors) to _search_ these researchers in the database based on their names. Loop through the list and, for each researcher in your list, find: 
>     - their _id_: The OpenAlex ID for this author.
>     - their _display\_name_: The name of the author as a single string.
>     - their _works\_api\_url_: A URL that will get you a list of all this author's works.
>     - their _h\_index_ : The h-index for this author.
>     - their _works\_count_: The number of  Works this this author has created.
>     - their _country\_code_: The country code of their last known institution
> 2. **Data Storage** Store this information in a Pandas DataFrame and save it to file.
>
>    
> **Handling Challenges**
> 
> I expect that, while working on the steps above, you will encounter several obstacles. As you complete this exercise, you are expected to:     
>
>    - Identify problems that arise.      
>    - Improve your solutions to address such problems, making reasonable decisions when data is incomplete or ambiguous.       
>
> **Reflection Questions**
>  Answer the following questions __(max 150 words for each question)__: 
>
>    - Which challenges did you encounter? How did you address them?
>    - Choose one problem you faced while collecting the data and describe your solution. Why did you choose this approach, and what impact might it have on your data? 
>

## Part 3: Collect Research Articles

> **Exercise 1: Collecting Research Articles from IC2S2 Authors**
>
>In this exercise, we'll leverage the OpenAlex API to gather information on research articles authored by participants of the IC2S2 2025 conference, referred to as *IC2S2 authors*. **Before you start, please ensure you read through the entire exercise.**
>
> 
> **Steps:**
>  
> 1. **Retrieve Data:** Start with the dataset of *IC2S2 authors* you collected in Week 2, Exercise 3 (called dataset D1 in the figure above). Use the OpenAlex API [works endpoint](https://docs.openalex.org/api-entities/works) to fetch their research articles. For each article, retrieve the following details:
>    - _id_: The unique OpenAlex ID for the work.
>    - _publication_year_: The year the work was published.
>    - _cited_by_count_: The number of times the work has been cited by other works.
>    - _author_ids_: The OpenAlex IDs for the authors of the work.
>    - _title_: The title of the work.
>    - _abstract_inverted_index_: The abstract of the work, formatted as an inverted index.
> 
>     **Important Note on Paging:** By default, the OpenAlex API limits responses to 25 works per request. For more efficient data retrieval, I suggest to adjust this limit to 200 works per request. Even with this adjustment, you will need to implement pagination to access all available works for a given query. This ensures you can systematically retrieve the complete set of works beyond the initial 200. Find guidance on implementing pagination [here](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/paging#cursor-paging).
>
> 2. **Data Storage:** Organize the retrieved information into two Pandas DataFrames and save them to two files in a suitable format:
>    - Dataset D2: The *IC2S2 papers* dataset should include: *id, publication\_year, cited\_by\_count, author\_ids*.
>    - Dataset D3: The *IC2S2 abstracts* dataset should include: *id, title, abstract\_inverted\_index*.
>  
>
> **Filters:**
> To ensure the data we collect is relevant and manageable, apply the following filters:
>     
>    - Only include *IC2S2 authors* with a total work count between 5 and 5,000.    
>    - Retrieve only works that have received more than 10 citations.    
>    - Limit to works authored by fewer than 10 individuals.    
>    - Include only works relevant to Computational Social Science (focusing on: Sociology OR Psychology OR Economics OR Political Science) AND intersecting with a quantitative discipline (Mathematics OR Physics OR Computer Science), as defined by their [Concepts](https://docs.openalex.org/api-entities/works/work-object#concepts). *Note*: here we only consider Concepts at *level=0* (the most coarse definition of concepts).     
>
> **Efficiency Tips:**
> Writing efficient code in this exercise is **crucial**. To speed up your process:
> 
> - **Apply filters directly in your request:** When possible, use the [filter parameter](https://docs.openalex.org/api-entities/works/filter-works) of the *works* endpoint to apply the filters above directly in your API request, ensuring only relevant data is returned. Learn about combining multiple filters [here](https://docs.openalex.org/how-to-use-the-api/get-lists-of-entities/filter-entity-lists).  
> - **Bulk requests:** Instead of sending one request for each author, you can use the [filter parameter](https://docs.openalex.org/api-entities/works/filter-works) to query works by multiple authors in a single request. *Note: My testing suggests that can only include up to 25 authors per request.*
> - **Use multiprocessing:** Implement multiprocessing to handle multiple requests simultaneously. I highly recommmend [Joblib’s Parallel](https://joblib.readthedocs.io/en/stable/) function for that, and [tqdm](https://tqdm.github.io/) can help monitor progress of your jobs. Remember to stay within [the rate limit](https://docs.openalex.org/how-to-use-the-api/rate-limits-and-authentication) of 100 requests per second.
>
>
>   
> For reference, employing these strategies allowed me to fetch the data in about 30 seconds using 5 cores on my laptop. I obtained a dataset of approximately 25 MB (including both the *IC2S2 abstracts* and *IC2S2 papers* files).
> 
>
> **Data Overview and Reflection questions:** Answer the following questions __(max 150 words for each question)__: 
> 
> - **Dataset summary.** How many works are listed in your Dataset D2 (*IC2S2 papers*) dataframe? How many unique researchers have co-authored these works?     
> - **Efficiency in code.** Describe the strategies you implemented to make your code more efficient. How did your approach affect your code's execution time?    
> - **Filtering Criteria and Dataset Relevance** Reflect on the rationale behind setting specific thresholds for the total number of works by an author, the citation count, the number of authors per work, and the relevance of works to specific fields. How do these filtering criteria contribute to the relevance of the dataset you compiled? Do you believe any aspects of Computational Social Science research might be underrepresented or overrepresented as a result of these choices?

# Assignment 1 solution

Github Link: https://github.com/WilliamKentoRasmussen/assignment-1-computational-social-science

Contributions:

Julie:
William:
Elisabeth:

In [43]:
# Imports
import pandas as pd
import numpy as np
import requests
import os
from dotenv import load_dotenv
from concurrent.futures import ThreadPoolExecutor
from joblib import Parallel, delayed
from tqdm.notebook import tqdm
import ast
from functools import partial

load_dotenv()

True

## Part 1: Ready made vs Custom made data

> 1. What are pros and cons of the custom-made data used in Centola's experiment (the first study presented in the lecture) and the ready-made data used in Nicolaides's study (the second study presented in the lecture)? You can support your arguments based on the content of the lecture and the information you read in Chapter 2.3 of the book.

The advantages from the custom-made data in Centola’s experiment are largely that the researchers had full control over the experimental setup. The data is thus very clean and can expose casual relationships/ smaller tendencies. The users also did not know that they were a part of a research experiment, so they did not have a bias in performance. However, it was an artificial environment, which may not be able to mimic the complexity of information spread in real life custom-made data is also costly to obtain. 

The ready-made data experiment has the advantage of data showing real-life interactions. However, as the data is from a social media platform, the users may still exhibit a bias in their behavior since they are being watched by the other users. Ready-made data can also be incomplete or dirty, making it hard to work with.


> 2. How do you think these differences can influence the interpretation of the results in each study? 

Centola’s experiment can be regarded as an experiment which has stripped group dynamics into a very bare-boned structure. It shows us how information can spread amongst people, but it does not fully describe the complex interaction between humans in real life. Thus, it can be one puzzle piece used to understand human interactions. The other experiment can be used to show how interactions happen in real life, but it will be hard to diagnose the underlying reasons why people are influencing each other the way they do.

## Part 2: Find Researchers using the openAlex API

### Steps
1. Retrive Data

In [69]:
# Import unique organizer names found in the IC2S2 conference in 2025 (originally found by web scraping)
organizer_names_df = pd.read_csv("./data/organizer_names.csv")
organizer_names_df

                       Name
0           marc keuschnigg
1                 sonia yeh
2            peter hedström
3            nina tahmasebi
4                elliot ash
...                     ...
1576          carl nordlund
1577     christian steglich
1578            neha gondal
1579  victor møller poulsen
1580            munjung kim

[1581 rows x 1 columns]

In [70]:
#Setup configuration for openalexnet API endpoint for data retrievel
BASE_URL = "https://api.openalex.org/"
RESOURCE = "authors"
url = BASE_URL+RESOURCE
url

'https://api.openalex.org/authors'

In [71]:
#This function gets applied on all organizer names to find the desired fields
def get_author(name, API_KEY):

    local_params = {"search": name, "api_key": API_KEY}
    response = requests.get(url, local_params)
    response_json = response.json()

    if "results" in response_json and len(response_json["results"]) > 0: # Check if the person is in the database
        result = response_json["results"][0]
        try: # Throws an error, when the country code property cant be accessed
            country_code = result["last_known_institutions"][0]["country_code"]  
            return{
            "id": result["id"],
            "display_name": result["display_name"],
            "works_api_url": result["works_api_url"],
            "h_index": result["summary_stats"]["h_index"],
            "works_count": result["works_count"],
            "country_code": country_code
            }
        
        except: # Error: set country_code to NaN
            return{
            "id": result["id"],
            "display_name": result["display_name"],
            "works_api_url": result["works_api_url"],
            "h_index": result["summary_stats"]["h_index"],
            "works_count": result["works_count"],
            "country_code": np.nan
            }
            
    
    else: # Name does not exist in the data base. Set all fields to NaN
            return{
            "id": np.nan,
            "display_name": np.nan,
            "works_api_url": np.nan,
            "h_index": np.nan,
            "works_count": np.nan,
            "country_code": np.nan
            }

In [72]:
# Applies the get_author function to all organizer_names_df names in parralel using the ThreadPoolExecutor package.

# Batch 1 of authors
API_KEY = os.getenv('JULIE_API_KEY_2')
with ThreadPoolExecutor(max_workers=10) as executor:
    results1 = list(executor.map(partial(get_author, API_KEY=API_KEY), list(organizer_names_df["Name"])[:790]))

# Batch 2 of authors
API_KEY = os.getenv('JULIE_API_KEY_4')
with ThreadPoolExecutor(max_workers=10) as executor:
    results2 = list(executor.map(partial(get_author, API_KEY=API_KEY), list(organizer_names_df["Name"])[790:]))

2. Data storage

In [73]:
# We store the results in a datafram and filter out the authors who do not have a working api url.
results = results1+results2
metadata_df = pd.DataFrame(results)
filtered_metadata_df = metadata_df[metadata_df["works_api_url"].notna()]
filtered_metadata_df

Empty DataFrame
Columns: [id, display_name, works_api_url, h_index, works_count, country_code]
Index: []

In [49]:
# The panda df can then be stored in a file
filtered_metadata_df.to_csv(r"data/D1.csv", index=False)

### Reflection Questions:

- Which challenges did you encounter? How did you address them?

A major challenge was the code's execution time. While performance varied across our different computers, the script generally took about seven minutes to run. To optimize this, we implemented parallel processing using the ThreadPoolExecutor library, allowing us to fetch metadata for multiple names simultaneously. Initially, we set the number of workers too high, which led to us exceeding the rate limit. We solved this by simply reducing the number of workers.

Our API Key also exceeded their daily limits very quickly. Just running all the people in a single call to the function `get_author()` would cause the daily limit to be surpassed. We thus had to split the authors in two batches and run each through the function on their own API key. Afterwards, we concatenated the results.


- Choose one problem you faced while collecting the data and describe your solution. Why did you choose this approach, and what impact might it have on your data? 

A problem we encountered was that some API author responses were invalid due to the given person not being in the data base or the author lacked certain properties, which was particularly problematic for nested fields. To address this, we implemented error handling for getting the nested field and added if statements to verify result lengths and field existence.

We resolved the issues of invalid responses and missing fields by replacing absent properties with NaN values. We chose this approach to retain the valid metadata associated with these authors. However, we decided to exclude people with invalid work URLs, as they would be not be of use in later in the assignment. These decisions will impact our future data handling, specifically, we will need to implement checks for NaN and maybe remove them later on.

## Part 3: Collect Research Articles

### Steps

1. Retrieve Data

In [57]:
# Reads D1 from the file saved just for fun and filters out authors without specified amount of works

# Filter
# Only include *IC2S2 authors* with a total work count between 5 and 5,000
D1 = pd.read_csv(r"data/D1.csv")
D1 = D1[(D1["works_count"] >= 5) & (D1["works_count"] <= 5000)].reset_index(drop=True)
D1

,id,display_name,works_api_url,h_index,works_count,country_code
0,https://openalex.org/A5058700879,Marc Keuschnigg,https://api.openalex.org/works?filter=author.i...,17.0,76.0,NaN
1,https://openalex.org/A5029945844,Sonia Yeh,https://api.openalex.org/works?filter=author.i...,41.0,224.0,GB
2,https://openalex.org/A5071769816,Peter Hedström,https://api.openalex.org/works?filter=author.i...,32.0,92.0,SE
3,https://openalex.org/A5003859694,Nina Tahmasebi,https://api.openalex.org/works?filter=author.i...,15.0,112.0,NaN
4,https://openalex.org/A5020654056,Hendrik Erz,https://api.openalex.org/works?filter=author.i...,2.0,40.0,NaN
...,...,...,...,...,...,...
1341,https://openalex.org/A5033663242,Carl Nordlund,https://api.openalex.org/works?filter=author.i...,6.0,24.0,SE
1342,https://openalex.org/A5030685996,Christian Steglich,https://api.openalex.org/works?filter=author.i...,42.0,104.0,NaN
1343,https://openalex.org/A5034089559,Neha Gondal,https://api.openalex.org/works?filter=author.i...,11.0,24.0,US
1344,https://openalex.org/A5059830287,Victor Møller Poulsen,https://api.openalex.org/works?filter=author.i...,2.0,7.0,US
1345,https://openalex.org/A5013327023,Munjung Kim,https://api.openalex.org/works?filter=author.i...,2.0,5.0,NaN

In [58]:
# Helper function for doing bulk request and getting the author_ID from openAlex_ID

def get_id(openalex_id):
    return openalex_id.split("/")[-1]

def chunked(authors, size):
    for i in range(0, len(authors), size):
        yield authors[i : i + size]

def build_works_url(author_batch):
    author_filter = "|".join(author_batch)
    return (
        f"https://api.openalex.org/works?filter=authorships.author.id:{author_filter}"
    )

# Applies the helper function to get the author batches.
original_authors_id = D1["id"].apply(get_id)
author_batches = list(chunked(original_authors_id, 25))

In [59]:
# Setup filters for the specified concepts
SOCIAL_CONCEPTS = {"Sociology", "Psychology", "Economics", "Political science"}
QUANT_CONCEPTS = {"Mathematics", "Physics", "Computer science"}


def is_relevant_concepts(article):
    concepts = article["concepts"]
    social = any(
        c["level"] == 0 and c["display_name"] in SOCIAL_CONCEPTS for c in concepts
    )
    quant = any(
        c["level"] == 0 and c["display_name"] in QUANT_CONCEPTS for c in concepts
    )
    return social and quant

In [60]:
#Get the work by authors in batches
def get_response(works_api_url, API_key):
    rows = []
    params = {"per_page": 200, "api_key": API_key, "cursor": "*"}

    session = requests.Session()
    session.headers.update({"User-Agent": "research-script/1.0"})

    while True:
        response = session.get(works_api_url, params=params, timeout=30)
        result = response.json()
        results = result["results"]

        for article in results:
            # Concepts filter
            if not is_relevant_concepts(article):
                continue

            authors = [
                authorship["author"]["id"] for authorship in article["authorships"]
            ]

            # Filter
            # Retrieve only works that have received more than 10 citations.
            # Limit to works authored by fewer than 10 individuals.
            if article["cited_by_count"] <= 10 or len(authors) >= 10:
                continue

            rows.append(
                {
                    "id": article["id"],
                    "publication_year": article["publication_year"],
                    "cited_by_count": article["cited_by_count"],
                    "author_ids": [
                        author.split("/")[-1]
                        for author in authors
                        if author is not None
                    ],
                    "title": article["title"],
                    "abstract_inverted_index": article["abstract_inverted_index"],
                }
            )

        next_cursor = result["meta"]["next_cursor"]
        if not next_cursor:
            break
        params["cursor"] = next_cursor

    return pd.DataFrame(rows)

In [61]:
# Runs the code in parrallel using the Parallel library and the tqdm package to see the process.
def get_metadata_df(urls,API_key):
    metadata_list = Parallel(n_jobs=4)(
        delayed(get_response)(url, API_key) for url in tqdm(urls, desc="Fetching works (batched)")
    )

    # Filter out None results and duplicates and combine
    metadata_list = [df for df in metadata_list if df is not None and not df.empty]
    metadata_df = pd.concat(metadata_list, ignore_index=True)
    metadata_df = metadata_df.drop_duplicates(subset=["id"])

    return metadata_df

In [62]:
# Batch urls for different API keys because of rate limits
urls = [build_works_url(batch) for batch in author_batches]

urls1 = urls[:18]
urls2 = urls[18:36]
urls3 = urls[36:]

API_key1 = os.getenv("API_KEY")
API_key2 = os.getenv("ELSE_API_KEY")
API_key3 = os.getenv("JULIE_API_KEY_3")

get_matadata_df1 = get_metadata_df(urls1,API_key1)
get_matadata_df2 = get_metadata_df(urls2,API_key2)
get_matadata_df3 = get_metadata_df(urls3,API_key3)

metadata_df = pd.concat([get_matadata_df1,get_matadata_df2,get_matadata_df3])

Fetching works (batched):   0%|          | 0/18 [00:00<?, ?it/s]

Fetching works (batched):   0%|          | 0/18 [00:00<?, ?it/s]

Fetching works (batched):   0%|          | 0/18 [00:00<?, ?it/s]

2. Data storage

In [63]:
# Splits up the metadata and stores it in csv files
D2 = metadata_df[["id", "publication_year", "cited_by_count", "author_ids"]].copy()
D3 = metadata_df[["id", "title", "abstract_inverted_index"]].copy()

D2.to_csv("./data/D2.csv", index=False)
D3.to_csv("./data/D3.csv", index=False)

### Data Overview and Reflection questions

- **Dataset summary.** How many works are listed in your Dataset D2 (*IC2S2 papers*) dataframe? How many unique researchers have co-authored these works?     

The amount of works listed in the D2 dataframe can be seen by its amount of rows, which is 15223. 

To find the amount of unique researchers that have co-authored these works, we extract the author_ids column in D2 and convert it from a string of a list to an actual list. We then explode the dataframe to obtain one author per row. We utilize sets to get all unique original authors. We then make a set of all unique authors found in the papers. To obtain all unique coauthors, we substract `all_authors_set - original_authors_set`, and end up with 23145 unique coauthors.

In [64]:
D2

,id,publication_year,cited_by_count,author_ids
0,https://openalex.org/W2152796930,2010.0,1548,"[A5071769816, A5029640601]"
1,https://openalex.org/W2088900896,2000.0,1436,"[A5100661890, A5108538229, A5112454407, A51020..."
2,https://openalex.org/W1989597713,2009.0,1169,"[A5071165387, A5037969281]"
3,https://openalex.org/W2103177132,1999.0,1098,[A5029945844]
4,https://openalex.org/W4245013494,1999.0,1093,[A5029945844]
...,...,...,...,...
5167,https://openalex.org/W3103732528,2019.0,14,"[A5100572173, A5043029070, A5039315344, A50569..."
5168,https://openalex.org/W2617544931,1997.0,13,"[A5080030270, A5019212344, A5111454621]"
5169,https://openalex.org/W2990181595,2019.0,13,"[A5100572173, A5043029070, A5039315344, A50175..."
5171,https://openalex.org/W2949808870,2018.0,12,"[A5077461583, A5052854215, A5101457342, A51086..."
5172,https://openalex.org/W3034377381,2020.0,11,"[A5076146838, A5000760201, A5007117877, A50642..."

In [68]:
# Set of main/original authors
original_authors_set = set(original_authors_id)

# Set of ALL authors appearing in papers
all_authors = D2["author_ids"].explode()#apply(ast.literal_eval).explode()
all_authors_set = set(all_authors)

# Co-authors set
coauthors_set = all_authors_set - original_authors_set

print(f"Original authors: {len(original_authors_set)}")
print(f"All authors: {len(all_authors_set)}")
print(f"Coauthors to fetch: {len(coauthors_set)}")

Original authors: 1329
All authors: 24237
Coauthors to fetch: 23199

- **Efficiency in code.** Describe the strategies you implemented to make your code more efficient. How did your approach affect your code's execution time?    

Similar to Part A, we implemented parallel computing, this time utilizing the Parallel library, as our initial codebase was developed by a different group member. This transition significantly reduced the execution time.

A major improvement in efficiency also resulted from bulking 25 authors for every API call, which also ensured we did not exceed the daily limits on our API keys. Finally, we chose to implement filters at different stages. For example, filtering by the number of works per author before the API calls further reduced the amount of API calls and thereby the execution time.


- **Filtering Criteria and Dataset Relevance** Reflect on the rationale behind setting specific thresholds for the total number of works by an author, the citation count, the number of authors per work, and the relevance of works to specific fields. How do these filtering criteria contribute to the relevance of the dataset you compiled? Do you believe any aspects of Computational Social Science research might be underrepresented or overrepresented as a result of these choices?  

Each filter serves different purposes. The rationale behind setting these thresholds seem to avoid including authors and papers with little impact (small total works count or small number of citations). We also want to avoid authors that publish too many papers (big total works count) which could stretch the research out of computational social science.

We want papers that have more than 1 author to be able to analyze the research collaboration in the field. We do not want papers that have too many authors as this might not be a paper relevant for computational social science.

Including concepts only relevant to computational social science and quantitative disciplines is clearly meant to capture the interaction between these very different fields that is unique in computational social science. Requiring only quantitative disciplines might leave out some humanitarian authors and their perspectives on the field of social science.